"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    'colours.py',
    'widgets.py',
    'light_copy_icon.png',
    'Dark_copy_icon.png',
    'Dark_cross_icon.png',
    'icons/trash.png',
    'icons/save-01.png',
    'icons/plus.png',
    'icons/folder-search.png',
    'icons/folder-plus.png',
    'icons/folder-open.png',
    'icons/copy-06.png',
    'icons/dropper.png',
    'icons/x-close.png'
    ]

OPTIONS = {
    'packages': [
        'tkinter',
        'json',
        'PIL',
        'mss',
        'os',
        'time'
        ]}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
