"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    'colours.py',
    'widgets.py',
    'light_copy_icon.png',
    'Dark_copy_icon.png',
    'Dark_cross_icon.png']

OPTIONS = {
    'packages': ['tkinter', 'json', 'pillow']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
